#this is to configure API service which need to your application
version: '3.8'
secrets:
  api:
    build: ./api
    container_name: inq_c
    port:
    - '4000:4000'
    volumes:
    - ./api:/app
    - ./app/node_modules

  inquiry:
    build: ./inquiry
    container_name: inquiry_c
    port:
      - '3000:3000'
    stdin_open: true
    tty : true
   
